version = "2.45.1"
build = """
tar xf binutils-2.45.1.tar.xz
cd binutils-2.45.1
mkdir -v build
cd build
../configure --prefix=/usr       \
             --sysconfdir=/etc   \
             --enable-ld=default \
             --enable-plugins    \
             --enable-shared     \
             --disable-werror    \
             --enable-64-bit-bfd \
             --enable-new-dtags  \
             --with-system-zlib  \
             --enable-default-hash-style=gnu
make tooldir=/usr
make DESTDIR=$PACKAGE_OUT tooldir=/usr install
"""

[[distfiles]]
uri = "https://ftpmirror.gnu.org/binutils/binutils-2.45.1.tar.xz"
blake2b = "cc326a83d0b9a95c75b27ff2ebe2cbae8c83791ff9a963fc1ebf95cd7587c16d"
