version = "2.6.4"
build = """
tar xf flex-2.6.4.tar.gz
cd flex-2.6.4
./configure --prefix=/usr
make
make DESTDIR=$PACKAGE_OUT install
ln -sv flex   $PACKAGE_OUT/usr/bin/lex
ln -sv flex.1 $PACKAGE_OUT/usr/share/man/man1/lex.1
"""
depends = ["m4"]

[[distfiles]]
uri = "https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"
blake2b = "8b24ced0d277ca97b56ad4b649b424784036e09cdbba05b7382c72450541042c"
