version = "5.3.2"
build = """
tar xf gawk-5.3.2.tar.xz
cd gawk-5.3.2
sed -i 's/extras//' Makefile.in
./configure --prefix=/usr
make
make DESTDIR=$PACKAGE_OUT install
"""

[[distfiles]]
uri = "https://ftpmirror.gnu.org/gawk/gawk-5.3.2.tar.xz"
blake2b = "6781edb1cd71a1e0e2d54e2d1d91a41b1b7e8046fcd813733569d1f8df1ff2a4"
