version = "15.2.0"
build = """
tar xf gcc-15.2.0.tar.xz
cd gcc-15.2.0
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac
mkdir build
cd build
../configure --prefix=/usr            \
             LD=ld                    \
             --enable-languages=c,c++ \
             --enable-default-pie     \
             --enable-default-ssp     \
             --enable-host-pie        \
             --disable-bootstrap      \
             --disable-fixincludes    \
             --with-system-zlib
make
make DESTDIR=$PACKAGE_OUT install
"""

[[distfiles]]
uri = "https://ftpmirror.gnu.org/gcc/gcc-15.2.0/gcc-15.2.0.tar.xz"
blake2b = "04798cd2d6b5300d653c83cd47236a233941228899b8c402a03997d3439b847f"
