version = "3.1.3"
build = """
tar xf libjpeg-turbo-3.1.3.tar.gz
cd libjpeg-turbo-3.1.3
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_BUILD_TYPE=RELEASE \
      -D ENABLE_STATIC=FALSE \
      -D CMAKE_INSTALL_DEFAULT_LIBDIR=lib \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
      -D CMAKE_SKIP_INSTALL_RPATH=ON \
      -D WITH_JPEG8=ON \
      ..
make
make DESTDIR=$PACKAGE_OUT install
"""
depends = ["cmake", "nasm"]

[[distfiles]]
uri = "https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/3.1.3/libjpeg-turbo-3.1.3.tar.gz"
blake2b = "51ac1492ab98ff8b16bb13474a3e4501c59ce7e9"
