version = "3.6.0"
build = """
tar xf openssl-3.6.0.tar.gz
cd openssl-3.6.0
./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic
make
sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
make MANSUFFIX=ssl DESTDIR=$PACKAGE_OUT install
"""
depends = ["perl"]

[[distfiles]]
uri = "https://github.com/openssl/openssl/releases/download/openssl-3.6.0/openssl-3.6.0.tar.gz"
blake2b = "130043946b3932ad5492b94cbddb90eed3cb56ede11730547f03161897857c08"
