version = "5.42.0"
build = """
tar xf perl-5.42.0.tar.gz
cd perl-5.42.0
export BUILD_ZLIB=False
export BUILD_BZIP2=0
sh Configure -des                                          \
             -D prefix=/usr                                \
             -D vendorprefix=/usr                          \
             -D privlib=/usr/lib/perl5/5.42/core_perl      \
             -D archlib=/usr/lib/perl5/5.42/core_perl      \
             -D sitelib=/usr/lib/perl5/5.42/site_perl      \
             -D sitearch=/usr/lib/perl5/5.42/site_perl     \
             -D vendorlib=/usr/lib/perl5/5.42/vendor_perl  \
             -D vendorarch=/usr/lib/perl5/5.42/vendor_perl \
             -D man1dir=/usr/share/man/man1                \
             -D man3dir=/usr/share/man/man3                \
             -D pager="/usr/bin/less -isR"                 \
             -D useshrplib                                 \
             -D usethreads
make
make DESTDIR=$PACKAGE_OUT install
unset BUILD_ZLIB BUILD_BZIP2
"""
depends = ["less"]

[[distfiles]]
uri = "https://www.cpan.org/src/5.0/perl-5.42.0.tar.gz"
blake2b = "ea815c870204f1c2c1302c056f101f395cbb86224fb939e26f8c91ca04e8d9f2"
