version = "1.3.1"
build = """
tar xf zlib-1.3.1.tar.xz
cd zlib-1.3.1
./configure --prefix=/usr
make
make DESTDIR=$PACKAGE_OUT install
"""

[[distfiles]]
uri = "https://www.zlib.net/zlib-1.3.1.tar.xz"
blake2b = "16c4c06da4f6452184243a0032c717c53a38c74aaa2e930fe43ad644f2de6fbf"
