version = "1.5.7"
build = """
tar xf zstd-1.5.7.tar.gz
cd zstd-1.5.7
make
make DESTDIR=$PACKAGE_OUT PREFIX=/usr install
"""

[[distfiles]]
uri = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz"
blake2b = "ebd372a97791ac8c0f6e2240aef57d38a77848af75f450d75f62fa146e45d47d"
